import { Inter } from "next/font/google";
import Header from './components/Header';
import Container from '@mui/material/Container';
import CssBaseline from '@mui/material/CssBaseline';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CssBaseline />
        <Header /> {/* Include Header */}
        <main>
          <Container sx={{ mt: 10 }}> {/* Adjust margin-top to avoid overlap */}
            {children}
          </Container>
        </main>
      </body>
    </html>
  );
}
